ALTER TABLE booking
DROP CONSTRAINT FK_BOOKING_ON_REVIEW;

ALTER TABLE booking
DROP COLUMN review_id;

ALTER TABLE bookingreview
    ADD COLUMN booking_id BIGINT NULL;

ALTER TABLE bookingreview
    ADD CONSTRAINT FK_BOOKINGREVIEW_ON_BOOKING FOREIGN KEY (booking_id) REFERENCES booking (id);
